name: Build, Deploy to Google Artifact Registry, and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      # Step 3: Setup Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Step 4: Authenticate Docker to Google Artifact Registry
      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Step 5: Build the Docker Image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/core-dev-435517/transcription-pioneer/flaskinferencecleaning:0.1 .

      # Step 6: Push Docker Image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/core-dev-435517/transcription-pioneer/flaskinferencecleaning:0.1

      # Step 7: Deploy Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy flaskinferencecleaning \
            --image us-central1-docker.pkg.dev/core-dev-435517/transcription-pioneer/flaskinferencecleaning:0.1 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      # Step 8: Retrieve and display the deployed URL (optional)
      - name: Get Deployed URL
        run: |
          URL=$(gcloud run services describe flaskinferencecleaning --platform managed --region us-central1 --format 'value(status.url)')
          echo "Deployed Service URL: $URL"
